spring:
#  datasource: 数据源统一放到属性文件里配置了
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bookshop?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: cpusky
  profiles:
    active: mybatis,dataSource
  output:
    ansi:
      enabled: always #彩色日志
  http:
      multipart:
        location: /Users/jianghui/Downloads/temp-del
debug: false
server:
  jsp-servlet:
    init-parameters: #servlet启动参数
      a: 1
      b: 2
#security:
#  basic:
#    authorize-mode: none #不启用spring security

#https://docs.spring.io/spring-boot/docs/1.4.7.RELEASE/reference/htmlsingle/#boot-features-logging 26章
#显式切换日志组件，默认是logback，logback的配置文件在spring发行包里是自带的，可以使用属性或者xml文件调整logback的配置
#见spring-boot-1.5.8包里的org.springframework.boot.logging.log4j2、org.springframework.boot.logging.logback、org.springframework.boot.logging.java等
logging:
  config: classpath:log4j2.xml
#  config: classpath:org/springframework/boot/logging/logback/base.xml

#tk 通用mapper配置  
#mapper:
#  mappers:
#    - mapper
#  notEmpty: true

#可以定义相同属性在不同profile下的不同值
---
spring:
  profiles: dev
debug: true